# Generated by Django 6.0.7 on 2026-07-31 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProblemProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('not_attempted', 'Not attempted'), ('attempted', 'Attempted'), ('partial', 'Partially solved'), ('solved', 'Solved')], db_index=True, default='not_attempted', max_length=16)),
                ('best_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('genuine_attempt_count', models.PositiveIntegerField(default=0)),
                ('first_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('first_solved_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('editorial_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('hint_used', models.BooleanField(default=False)),
                ('has_mastery', models.BooleanField(db_index=True, default=False)),
                ('best_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submissions.submission')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_problem_progress',
                'indexes': [models.Index(fields=['user', 'state'], name='idx_progress_user_state'), models.Index(fields=['user', 'has_mastery'], name='idx_progress_user_mastery'), models.Index(fields=['problem', 'state'], name='idx_progress_problem_state')],
                'constraints': [models.UniqueConstraint(fields=('user', 'problem'), name='uniq_user_problem_progress')],
            },
        ),
    ]
