# Generated by Django 6.0.7 on 2026-07-31 15:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('statement', models.TextField(blank=True)),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='easy', max_length=16)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('solved_count', models.PositiveIntegerField(default=0)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'problems',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('time_limit_ms', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(100)])),
                ('memory_limit_mb', models.PositiveIntegerField(default=256, validators=[django.core.validators.MinValueValidator(16)])),
                ('output_limit_kb', models.PositiveIntegerField(default=8192)),
                ('comparison_mode', models.CharField(choices=[('exact', 'Exact after whitespace normalisation'), ('float', 'Floating point within tolerance'), ('checker', 'Custom checker')], default='exact', max_length=16)),
                ('float_tolerance', models.FloatField(blank=True, null=True)),
                ('checker_source', models.TextField(blank=True)),
                ('checker_language', models.CharField(blank=True, max_length=32)),
                ('language_images', models.JSONField(blank=True, default=dict)),
                ('rubric', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('change_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='problems.problem')),
            ],
            options={
                'db_table': 'problem_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='problems.problemversion'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='problems', to='problems.tag'),
        ),
        migrations.CreateModel(
            name='TestGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_sample', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('problem_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_groups', to='problems.problemversion')),
            ],
            options={
                'db_table': 'test_groups',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('input_key', models.CharField(blank=True, max_length=512)),
                ('expected_output_key', models.CharField(blank=True, max_length=512)),
                ('input_data', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('input_sha256', models.CharField(blank=True, max_length=64)),
                ('expected_output_sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.testgroup')),
            ],
            options={
                'db_table': 'test_cases',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='problemversion',
            constraint=models.UniqueConstraint(fields=('problem', 'version_number'), name='uniq_problem_version_number'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_public', 'difficulty'], name='problems_is_publ_b48c64_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['author', '-created_at'], name='problems_author__c391ce_idx'),
        ),
        migrations.AddIndex(
            model_name='testgroup',
            index=models.Index(fields=['problem_version', 'is_sample'], name='test_groups_problem_c9d72a_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['test_group', 'order'], name='test_cases_test_gr_c8408a_idx'),
        ),
    ]
