# Generated by Django 6.0.7 on 2026-08-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemversion',
            name='judge_mode',
            field=models.CharField(choices=[('io', 'I/O (stdin/stdout)'), ('signature', 'Function signature')], db_index=True, default='io', max_length=16),
        ),
        migrations.AddField(
            model_name='problemversion',
            name='signature_templates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
