# Generated by Django 6.0.7 on 2026-07-31 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('user.role_changed', 'User role changed'), ('user.disabled', 'User disabled'), ('user.enabled', 'User enabled'), ('user.mfa_reset', 'User MFA reset'), ('user.impersonation_started', 'Impersonation started'), ('problem.created', 'Problem created'), ('problem.updated', 'Problem updated'), ('problem.deleted', 'Problem soft-deleted'), ('problem.version_published', 'Problem version published'), ('test_data.read', 'Hidden test data read'), ('test_data.uploaded', 'Test data uploaded'), ('checker.changed', 'Custom checker changed'), ('rejudge.started', 'Rejudge started'), ('rejudge.completed', 'Rejudge completed'), ('contest.created', 'Contest created'), ('contest.state_changed', 'Contest state changed'), ('contest.finalized', 'Contest finalized'), ('contest.rejudge_after_final', 'Rejudge after finalization'), ('contest.standings_adjusted', 'Standings adjusted'), ('contest.participant_disqualified', 'Participant disqualified'), ('editorial.released', 'Editorial released'), ('editorial.unlocked', 'Editorial unlocked for user')], db_index=True, max_length=64)),
                ('actor_label', models.CharField(blank=True, max_length=255)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id', '-created_at'], name='audit_log_target__3aa5a1_idx'), models.Index(fields=['actor', '-created_at'], name='audit_log_actor_i_91cd96_idx'), models.Index(fields=['action', '-created_at'], name='audit_log_action_7c9e02_idx')],
            },
        ),
    ]
