# Generated by Django 6.0.7 on 2026-07-31 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('running', 'Running'), ('frozen', 'Frozen'), ('paused', 'Paused'), ('ended', 'Ended'), ('provisional', 'Provisional'), ('final', 'Final')], db_index=True, default='draft', max_length=16)),
                ('resume_state', models.CharField(blank=True, max_length=16)),
                ('scoring_mode', models.CharField(choices=[('partial', 'Partial (sum of best scores)'), ('icpc', 'ICPC (solved count, then penalty)')], default='partial', max_length=16)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('freeze_at', models.DateTimeField(blank=True, null=True)),
                ('paused_duration_seconds', models.PositiveIntegerField(default=0)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('grace_period_seconds', models.PositiveIntegerField(default=0)),
                ('penalty_minutes_per_wrong', models.PositiveIntegerField(default=20)),
                ('is_rated', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('rules_text', models.TextField(blank=True)),
                ('tiebreak_rule', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_contests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contests',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=100)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contest_appearances', to='problems.problem')),
                ('problem_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='problems.problemversion')),
            ],
            options={
                'db_table': 'contest_problems',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('participated', 'Participated'), ('unofficial', 'Unofficial'), ('virtual', 'Virtual'), ('disqualified', 'Disqualified')], db_index=True, default='registered', max_length=16)),
                ('virtual_started_at', models.DateTimeField(blank=True, null=True)),
                ('rating_before', models.IntegerField(blank=True, null=True)),
                ('rating_after', models.IntegerField(blank=True, null=True)),
                ('disqualified_reason', models.TextField(blank=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contest_registrations',
            },
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['state', 'starts_at'], name='contests_state_ac3b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['is_public', '-starts_at'], name='contests_is_publ_90ec73_idx'),
        ),
        migrations.AddConstraint(
            model_name='contestproblem',
            constraint=models.UniqueConstraint(fields=('contest', 'problem'), name='uniq_contest_problem'),
        ),
        migrations.AddConstraint(
            model_name='contestproblem',
            constraint=models.UniqueConstraint(fields=('contest', 'label'), name='uniq_contest_problem_label'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['contest', 'status'], name='contest_reg_contest_50e557_idx'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('contest', 'user'), name='uniq_contest_registration'),
        ),
    ]
