# Generated by Django 6.0.7 on 2026-08-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_append_only_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user.role_changed', 'User role changed'), ('user.disabled', 'User disabled'), ('user.enabled', 'User enabled'), ('user.password_changed', 'User password changed'), ('user.mfa_reset', 'User MFA reset'), ('user.impersonation_started', 'Impersonation started'), ('problem.created', 'Problem created'), ('problem.updated', 'Problem updated'), ('problem.deleted', 'Problem soft-deleted'), ('problem.version_published', 'Problem version published'), ('test_data.read', 'Hidden test data read'), ('test_data.uploaded', 'Test data uploaded'), ('checker.changed', 'Custom checker changed'), ('rejudge.started', 'Rejudge started'), ('rejudge.completed', 'Rejudge completed'), ('contest.created', 'Contest created'), ('contest.state_changed', 'Contest state changed'), ('contest.finalized', 'Contest finalized'), ('contest.rejudge_after_final', 'Rejudge after finalization'), ('contest.standings_adjusted', 'Standings adjusted'), ('contest.participant_disqualified', 'Participant disqualified'), ('editorial.released', 'Editorial released'), ('editorial.unlocked', 'Editorial unlocked for user')], db_index=True, max_length=64),
        ),
    ]
