# Generated by Django 6.0.7 on 2026-07-31 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('run', 'Run (sample tests only)'), ('submit', 'Submit (all test groups)')], default='submit', max_length=16)),
                ('language', models.CharField(db_index=True, max_length=32)),
                ('language_image', models.CharField(blank=True, max_length=255)),
                ('source_code', models.TextField()),
                ('source_bytes', models.PositiveIntegerField(default=0)),
                ('verdict', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('compiling', 'Compiling'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('output_limit_exceeded', 'Output Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compile_error', 'Compile Error'), ('presentation_error', 'Presentation Error'), ('sandbox_violation', 'Sandbox Violation'), ('internal_error', 'Internal Error'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('raw_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_runtime_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('max_memory_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('compile_output', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('rejudge_count', models.PositiveIntegerField(default=0)),
                ('is_rejudging', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='problems.problem')),
                ('problem_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='problems.problemversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verdict', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('compiling', 'Compiling'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('output_limit_exceeded', 'Output Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compile_error', 'Compile Error'), ('presentation_error', 'Presentation Error'), ('sandbox_violation', 'Sandbox Violation'), ('internal_error', 'Internal Error'), ('cancelled', 'Cancelled')], db_index=True, max_length=32)),
                ('passed', models.BooleanField(default=False)),
                ('cases_total', models.PositiveIntegerField(default=0)),
                ('cases_passed', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('max_runtime_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('max_memory_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('first_failing_case_index', models.IntegerField(blank=True, null=True)),
                ('case_results', models.JSONField(blank=True, default=list)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='submissions.submission')),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='problems.testgroup')),
            ],
            options={
                'db_table': 'submission_results',
                'ordering': ['test_group__order'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-received_at'], name='idx_sub_user_recent'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem', '-received_at'], name='idx_sub_user_problem'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', 'verdict'], name='idx_sub_problem_verdict'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['contest', '-received_at'], name='idx_sub_contest'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(condition=models.Q(('verdict__in', ['pending', 'queued', 'compiling', 'running'])), fields=['received_at'], name='idx_sub_pending'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='uniq_submission_idempotency'),
        ),
        migrations.AddIndex(
            model_name='submissionresult',
            index=models.Index(fields=['submission', 'verdict'], name='submission__submiss_d17914_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissionresult',
            constraint=models.UniqueConstraint(fields=('submission', 'test_group'), name='uniq_result_per_group'),
        ),
    ]
